language: php

php:
  - 7.1

services:
  - mysql

before_script:
  - mkdir storage
  - mkdir storage/app
  - mkdir storage/framework
  - mkdir storage/framework/sessions
  - mkdir storage/framework/cache
  - mkdir storage/framework/views
  - chmod 777 -R storage
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - mysql -u root -e 'CREATE DATABASE dashboard_test;'
  - php artisan migrate

script:
  - php artisan key:generate
  - ./vendor/bin/phpunit